### ISSUE TITLE
Script Runtime Error

### ISSUE THREAD

**Issue by KJAERBYHF** [ws-cs2/cs2-surftimer#2]
Nov  7 09:58:05:  Script Runtime Error: /home/dathost/cs2_linux/game/csgo/scripts/vscripts/wst.lua:130: bad argument #1 to 'gmatch' (string expected, got nil)
Nov  7 09:58:05:  stack traceback:
Nov  7 09:58:05:  #011[C]: in function 'gmatch'
Nov  7 09:58:05:  #011/home/dathost/cs2_linux/game/csgo/scripts/vscripts/wst.lua:130: in function 'SplitVectorString'
Nov  7 09:58:05:  #011/home/dathost/cs2_linux/game/csgo/scripts/vscripts/wst.lua:145: in function 'LoadZones'
Nov  7 09:58:05:  #011/home/dathost/cs2_linux/game/csgo/scripts/vscripts/wst.lua:163: in function 'runscript'
Nov  7 09:58:05:  #011scripts/vscripts/utils/vscriptinit.lua:70: in function <scripts/vscripts/utils/vscriptinit.lua:58>

Installed everything as per the instructions

**Comment by ws-cs2** [comment]
hey @KJAERBYHF can you jump in here and I'll debug this with you https://discord.gg/CuggVmx9

**Comment by KJAERBYHF** [comment]
> hey @KJAERBYHF can you jump in here and I'll debug this with you https://discord.gg/CuggVmx9

For sure, thanks!

**Comment by ws-cs2** [comment]
Resolved this
