### ISSUE TITLE
Allow for 64 players

### ISSUE THREAD

**Issue by ws-cs2** [ws-cs2/cs2-surftimer#4]
Problem:

Currently people are restricting surf servers to `mp_humanteam CT` so people don't kill each other.

This has the problem of limiting 64 slot servers to 32 players. Above 32 players the CT team says it is full. I believe this is because maps only have 32 spawns for each team (I'm not a mapper I'm not too sure about this).

The fix for this will either be:

1. Can we allow CS2 to have more than 32 players on CT (is there some command none of the servers know about?)

2. Can we make CT/T invulnerable so that we can use both teams

The `god` command does not work on cs2.

I have see some discussion on forums about using a combination of 

```
buddha true
sv_regeneration_force_on true
```

I'm a bit lost as to how these commands work & how we can implement this in the timer

**Comment by ws-cs2** [comment]
Also happy for any sort of solution to this, either a set of commands, something we can do in lua or as a last resort in metamod.

**Comment by ws-cs2** [comment]
Testing a temporary fix where we convert all T spawns to CT spawns. This should fix most maps.

```

function ConvertTSpawnsToCTSpawns()
    for i, entity in pairs(Entities:FindAllByClassname("info_player_terrorist")) do
        SpawnEntityFromTableSynchronous("info_player_counterterrorist", { origin = entity:GetOrigin() } )
        entity:Kill()
    end
end
```

**Comment by Synkstar** [comment]
On surf kitsune it isnt fixed. ( Only allows 50 )
